---
kind: pipeline
type: docker
name: on_commit

steps:
  - name: test
    image: plugins/docker
    settings:
      target: test
      dry_run: true
      repo: registry.draive.gr/library/drone-template
      registry: registry.draive.gr
      tags:
        - latest

  - name: build
    image: plugins/docker
    settings:
      target: build
      dry_run: true
      repo: registry.draive.gr/library/drone-template
      registry: registry.draive.gr
      tags:
        - latest

  - name: discord_notification
    image: appleboy/drone-discord
    when:
      status:
        - failure
        - success
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN

trigger:
  branch:
    exclude:
      - master
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: on_push_master

steps:
  - name: test
    image: plugins/docker
    settings:
      target: test
      dry_run: true
      repo: registry.draive.gr/library/drone-template
      registry: registry.draive.gr
      tags:
        - latest

  - name: build
    image: plugins/docker
    settings:
      target: build
      dry_run: true
      repo: registry.draive.gr/library/drone-template
      registry: registry.draive.gr
      tags:
        - latest

  - name: publish
    image: plugins/docker
    settings:
      target: final
      repo: registry.draive.gr/library/drone-template
      registry: registry.draive.gr
      tags:
        - latest
      insecure: true
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD

  - name: discord_notification
    image: appleboy/drone-discord
    when:
      status:
        - failure
        - success
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN

trigger:
  branch:
    - master
  event:
    - push
